# Setup a basic environment for running the code
name: { { cookiecutter.project_slug } }
channels:
  - conda-forge
dependencies:
  - python={{ cookiecutter.python_version }}
  - numpy
  - matplotlib
  - jupyter
  # Test and style checkers
  - pytest
  - pytest-cov
  - coverage
  - black>=20.8b1
  - pylint
  - flake8
  - flake8-bugbear
