name: REPLACE_WITH_REPO_NAME
channels:
  - conda-forge
  - defaults
dependencies:
  # Should be on every project
  - python==3.12.*
  - pip
  - conda-lock
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyterlab
  - black
  # For building latex documents
  - make
  - tectonic
  # Project specific dependencies
  - pooch
  - verde
  - harmonica
  # Things that need to come from pip
  - pip:
    - black[jupyter]
